export const FETCH_CHARACTER_LIST = "FETCH_CHARACTER_LIST";
export const FETCH_CHARACTER_LIST_SUCCESS = "FETCH_CHARACTER_LIST_SUCCESS";
export const FETCH_CHARACTER_LIST_FAILED = "FETCH_CHARACTER_LIST_FAILED";
export const RESET_FILTERS = "RESET_FILTERS";
export const APPLY_FILTERS = "APPLY_FILTERS";
export const APPLY_SEARCHING_SORTING = "APPLY_SEARCHING_SORTING";

